name: Release Package
on:
  push:
    branches:
      - master
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: scripts/setup-npmrc.sh
        env:
          CI: true
      - run: yarn
        env:
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: yarn build
        env:
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: yarn test
        env:
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}
          CI: true
      - run: npx semantic-release
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
